version: '3.9'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - s3mock
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: deezer
      DB_USER: root
      DB_PASSWORD: example
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BULL_NAME: downloadQueue
      ACCESS_URL: http://s3mock:9090
      S3_ACCESS_KEY_ID: test
      S3_SECRET_ACCESS_KEY: test
      S3_REGION: us-east-1
      S3_BUCKET_NAME: deezar
      APP_PORT: 8000
      LOGO_URL: https://www.deezer.com/img/deezer-icon-white-logo.svg
      APP_URL: http://192.168.1.53:8000
      EMAIL_HOST: pro3.mail.ovh.net
      EMAIL_PORT: 587
      EMAIL_USER: contact@myecoria.com
      EMAIL_PASSWORD: password
      EMAIL_FROM: contact@myecoria.com
      DEEZER_KEY: 31ba52d78497a4c02f895c02788f7c38641947e4c082917ad335f9e2a5fa0aa4d528080aa53ea1ea733bac0be7617c008196ca9a22266921de5355b253b2806c63fe7356311f9106cc14980fd634bb4d6a31e135a6779911f0c3fe000c5bb1c7


  worker:
    build: ./worker
    depends_on:
      - db
      - redis
      - s3mock
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: deezer
      DB_USER: root
      DB_PASSWORD: example
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BULL_NAME: downloadQueue
      CONCURRENCY: 5
      ACCESS_URL: http://s3mock:9090
      S3_ACCESS_KEY_ID: test
      S3_SECRET_ACCESS_KEY: test
      S3_REGION: us-east-1
      S3_BUCKET_NAME: deezar
      DEEZER_KEY: arl_token

  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: deezer
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "3307:3306"
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6389:6379"
    restart: always

  s3mock:
    image: adobe/s3mock:latest
    ports:
      - "9091:9090"
    restart: always

volumes:
  db_data:
