name: Build and Release Binaries

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  master:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: linux
            asset: epico-linux
            output: epico-linux
          - target: macos
            asset: epico-macos
            output: epico-macos
          - target: win
            asset: epico-win.exe
            output: epico-win.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          npm run build
          npm run pkg:${{ matrix.target }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ matrix.output }}
          asset_name: ${{ matrix.asset }}
          tag: ${{ github.ref }}
          overwrite: true
  
  worker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: linux
            asset: worker-linux
            output: worker-linux
          - target: macos
            asset: worker-macos
            output: worker-macos
          - target: win
            asset: worker-win.exe
            output: worker-win.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./worker

      - name: Build project
        run: |
          npm run build
          npm run pkg:${{ matrix.target }}
        working-directory: ./worker

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./worker/${{ matrix.output }}
          asset_name: ${{ matrix.asset }}
          tag: ${{ github.ref }}
          overwrite: true
