name: Build and Release Binaries

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: linux
            asset: deezar-linux
            output: deezar-linux
          - target: macos
            asset: deezar-macos
            output: deezar-macos
          - target: win
            asset: deezar-win.exe
            output: deezar-win.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          npm run build
          npm run pkg:${{ matrix.target }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ matrix.output }}
          asset_name: ${{ matrix.asset }}
          tag: ${{ github.ref }}
          overwrite: true
